version: "3.8"
name: argo-docs

services:
  latexpdfbuilder:
    build: ./docker
    command: tail -F anything
    volumes:
      - ./commands:/data/commands
      - ../sources:/data/sources
      - ../Logo:/data/logo
      - ./build-output:/data/build-output
